SET(FOOD_VERSION 0.0.1)
SET(FOOD_MAJOR_VERSION 0)
SET(FOOD_MAJOR_MINOR_VERSION 000001)
SET(FOOD_VERSION_STRING "0.0.1 (Dev)")
SET(FOOD_ENABLE_DEVELOPMENT_MODE_DEFAULT ON) # Change to 'OFF' for a release
