#!/bin/bash

# iBase
wget https://redmine.scorec.rpi.edu/anonsvn/itaps/software/tags/1.3/interfaces/iBase/spec/iBase.h

mv iBase.h ../itaps/src/iBase.h

# iMesh
wget https://redmine.scorec.rpi.edu/anonsvn/itaps/software/tags/1.3/interfaces/iMesh/spec/iMesh.h

mv iMesh.h ../itaps/src/iMesh.h

# iGeom
wget https://redmine.scorec.rpi.edu/anonsvn/itaps/software/tags/1.3/interfaces/iGeom/spec/iGeom.h

mv iGeom.h ../itaps/src/iGeom.h

# iRel
wget https://redmine.scorec.rpi.edu/anonsvn/itaps/software/tags/1.3/interfaces/iRel/spec/iRel.h

mv iRel.h ../itaps/src/iRel.h

# iField
wget https://redmine.scorec.rpi.edu/anonsvn/itaps/software/tags/1.3/interfaces/iField/spec/iField.h

mv iField.h ../itaps/src/iField.h
