SET(SUBPACKAGES_DIRS_CLASSIFICATIONS_OPTREQS
  Utils            utils            SS  REQUIRED
  Discretization   discretization   SS  REQUIRED
  Field            field            SS  REQUIRED
  Search           search           SS  REQUIRED
  Transfer         transfer         SS  OPTIONAL
  ) 

SET(LIB_REQUIRED_DEP_PACKAGES)
SET(LIB_OPTIONAL_DEP_PACKAGES)
SET(TEST_REQUIRED_DEP_PACKAGES)
SET(TEST_OPTIONAL_DEP_PACKAGES)
SET(LIB_REQUIRED_DEP_TPLS)
SET(LIB_OPTIONAL_DEP_TPLS)
SET(TEST_REQUIRED_DEP_TPLS)
SET(TEST_OPTIONAL_DEP_TPLS)
